import { Bullets, Card, RDHeader } from "../_components";

export default function PropertiesPage() {
  return <div className="space-y-5"><RDHeader title="Properties" subtitle="Candidate Outpost sites, what we know, and what still needs verification before any commitment." />
    <Card title="Heber City / Wasatch Back" tag="Lead market"><Bullets items={["Heber has been treated as a leading candidate for Outpost #1 because it combines resident traffic, Wasatch Back access and year-round motorcycle reach.","A ±2.6-acre Heber opportunity was explored, with concept sizes around 3,200 / 4,000 / 4,800 SF.","Ideal Wasatch Back site brief: 0.75–1.25 acre, coffee + enclosed moto service, good access/parking/signage/patio, roll-up doors and expansion potential."]}/></Card>
    <Card title="Coalville — 2 S Main / Boyden Block" tag="Diligence"><Bullets items={["Historic Main Street opportunity explored in detail for coffee front / moto rear.","Working notes: roughly 5,366 SF total; first and second floors about 2,316 SF each, plus basement storage/support.","Known features discussed: AC, 24/7 access, elevator, bathrooms on both floors, second-floor break room and rear parking control.","Desired changes: rear bike access, glass garage doors, main-floor bathroom and basement storage.","City feedback identified CUP, parking, rear access, fire separation, ventilation, health department, signage and workshop limits as items to solve before commitment."]}/></Card>
    <Card title="Coalville — 21 S Main" tag="Alternative"><Bullets items={["Separate Coalville listing considered as a possible combined Outpost + APRISM building.","Approximate total area discussed around 5,572 SF, including a front retail/coffee component.","Potential attraction: offices in the middle / upper areas and a layout that may support shared operations.","Published details and exact floor plan still need to be treated as unverified until matched to source documents."]}/></Card>
    <Card title="Kamas / Francis" tag="Conditional"><Bullets items={["Kamas North Main and Francis opportunities have been investigated, including zoning, cash-offer and build-to-suit possibilities.","A Harwood Homes build-to-suit lead requires parcel, land size, sale vs ground lease vs BTS economics, entitlement, building scope and timeline confirmation.","Francis Town Center / 2217 S Spring Hollow Rd was a GO for investigation, not lease signing.","Current strategic role: possible future Basecamp location rather than an automatic first launch."]}/></Card>
    <Card title="Salt Lake City — Granary" tag="Future flagship"><Bullets items={["A roughly 3,900 SF Granary District space was studied for the combined concept.","Salt Lake remains a strong longer-term flagship idea because of population, motorcycle culture and destination potential.","The current direction is to prove the model before taking on the larger flagship risk."]}/></Card>
    <Card title="Published-plan references"><Bullets items={["Mountain View Commons 30 × 60 ft plan was selected as the strongest published-plan reference and adapted dimensionally for Outpost.","Other Utah properties compared included 1548 W American Way, 1559 W 2550 N and 1185 W 3050 S.","Evaluation focus: stairs/mezzanine, upper offices, bathrooms, overhead doors, parking, shop separation and future expansion."]}/></Card>
  </div>;
}
