import { Bullets, Card, RDHeader } from "../_components";

export default function DecisionsPage() {
  return <div className="space-y-5"><RDHeader title="Decisions" subtitle="The current Outpost decision log so earlier ideas do not quietly become commitments." />
    <Card title="Proceed" tag="Approved"><Bullets items={["Keep developing Outpost Coffee & Moto as an APRISM R&D initiative, not live coffee operations yet.","Continue proving Outpost Moto service as the near-term operating engine.","Use the ideal combined-building model: coffee + two Moto bays + one APRISM bay, with upper-floor offices and meeting room where practical.","Continue Wasatch Back property search and keep broader Utah aesthetic-fit opportunities on the radar.","Maintain the approved Outpost Coffee & Moto identity and Caffeine and Gasoline direction."]}/></Card>
    <Card title="Conditional / diligence"><Bullets items={["Coalville: interesting because of Main Street character and possible combined use, but CUP, parking, rear access, ventilation, fire separation and economics must work first.","Kamas / Francis: continue only where zoning, access, build economics and year-round demand support the concept.","Heber: strong candidate market, but site selection still needs disciplined underwriting.","Build-to-suit opportunities: investigate parcel control, entitlement, developer terms and timeline before treating them as real options."]}/></Card>
    <Card title="Hold"><Bullets items={["Salt Lake / Granary flagship remains attractive, but is better treated as a later-stage flagship until the operating model is proven.","Large capital commitment around the $800k development scale stays on hold until site, financing and downside economics are credible.","Coffee POS, inventory, staffing and vendor systems are intentionally not being built into APRISM HQ yet because Outpost coffee is not live operations."]}/></Card>
    <Card title="Reject / avoid"><Bullets items={["Do not turn Outpost into a full-service restaurant with a heavy kitchen and dinner operation.","Do not sign a lease or buy a building simply because the aesthetic fits if parking, service access, zoning or winter economics are weak.","Do not require extraordinary APRISM growth to make a property purchase pencil.","Do not let APRISM Property Services lose focus while Outpost is still in concept development."]}/></Card>
    <Card title="Current gate"><p className="text-[#f2eee5]">The next real commitment should happen only after a property passes the physical fit, land-use, operating economics and reserve tests.</p><p>Until then, Outpost remains a deliberately low-burn project room while APRISM Property Services and Outpost Moto generate proof.</p></Card>
  </div>;
}
