import { ArrowRight, CalendarDays, Camera, Plus } from "lucide-react";
import Link from "next/link";
import { HealthBadge } from "@/components/portal/health-badge";
import { Metric, Panel, PortalPageHeader } from "@/components/portal/portal-ui";
import { demoProperty, issues, maintenanceItems } from "@/lib/portal-data";

export default function PortalDashboardPage() {
  return (
    <main className="mx-auto max-w-[1480px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
      <PortalPageHeader eyebrow="Friday, August 28" title="Good morning, Alex." description="Here is the current operating picture for your property." action={<Link href="/portal/requests" className="inline-flex min-h-11 items-center justify-center gap-2 bg-[#1a1d1c] px-5 text-[0.58rem] font-semibold uppercase tracking-[0.15em] text-white"><Plus aria-hidden="true" className="size-4" />Service request</Link>} />
      <section className="mt-7 grid overflow-hidden border border-black/10 bg-[#171b19] text-white lg:grid-cols-[1.15fr_0.85fr]">
        <div className="portal-property-scene relative min-h-80 overflow-hidden p-6 sm:p-8"><div className="relative z-10 flex h-full flex-col justify-between"><p className="text-[0.56rem] font-semibold uppercase tracking-[0.2em] text-white/46">Primary property</p><div><HealthBadge status={demoProperty.health} /><h2 className="mt-5 font-serif text-4xl sm:text-5xl">{demoProperty.name}</h2><p className="mt-2 text-xs uppercase tracking-[0.14em] text-white/45">{demoProperty.location}</p></div></div></div>
        <div className="grid grid-cols-2 gap-px bg-white/10"><div className="bg-[#171b19] p-5 sm:p-7"><CalendarDays aria-hidden="true" className="size-4 text-[#c7a76b]" /><p className="mt-8 text-[0.54rem] uppercase tracking-[0.15em] text-white/35">Last inspection</p><p className="mt-2 text-sm">{demoProperty.lastInspection}</p></div><div className="bg-[#171b19] p-5 sm:p-7"><CalendarDays aria-hidden="true" className="size-4 text-[#c7a76b]" /><p className="mt-8 text-[0.54rem] uppercase tracking-[0.15em] text-white/35">Next visit</p><p className="mt-2 text-sm">{demoProperty.nextVisit}</p></div><Link href={`/portal/properties/${demoProperty.id}`} className="col-span-2 flex items-center justify-between bg-[#202421] p-5 text-[0.6rem] font-semibold uppercase tracking-[0.15em] text-[#d7ba82] sm:p-7">View property record <ArrowRight aria-hidden="true" className="size-4" /></Link></div>
      </section>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Property health" value="Monitor" detail="1 action recommended" /><Metric label="Open issues" value={demoProperty.openIssues} detail="No critical issues" /><Metric label="Upcoming maintenance" value={demoProperty.upcomingMaintenance} detail="Next 45 days" /><Metric label="Documents" value="28" detail="4 updated this season" /></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">
        <Panel title="Open issues" eyebrow="Attention"><div className="divide-y divide-black/10">{issues.map((issue) => <Link key={issue.title} href="/portal/issues" className="grid gap-4 px-5 py-5 transition hover:bg-black/[0.025] sm:grid-cols-[1fr_auto] sm:px-6"><div><HealthBadge status={issue.severity} /><h3 className="mt-3 text-sm font-medium">{issue.title}</h3><p className="mt-1 text-xs text-black/40">Opened {issue.opened} · {issue.owner}</p></div><ArrowRight aria-hidden="true" className="mt-2 size-4 text-black/28" /></Link>)}</div></Panel>
        <Panel title="Upcoming maintenance" eyebrow="Next 45 days"><div className="divide-y divide-black/10">{maintenanceItems.slice(0, 3).map((item) => <div key={item.title} className="flex items-center gap-4 px-5 py-4 sm:px-6"><div className="flex size-12 shrink-0 flex-col items-center justify-center border border-black/12 bg-white"><span className="text-[0.5rem] uppercase text-black/36">{item.date.split(" ")[0]}</span><span className="font-serif text-xl leading-none">{item.date.split(" ")[1]}</span></div><div><h3 className="text-sm font-medium">{item.title}</h3><p className="mt-1 text-xs text-black/40">{item.category} · {item.status}</p></div></div>)}</div></Panel>
      </div>
      <Panel title="Recent property photos" eyebrow="Last inspection" action={<Link href={`/portal/properties/${demoProperty.id}#photos`} className="text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-[#80632d]">View all</Link>} className="mt-5"><div className="grid gap-3 p-4 sm:grid-cols-3 sm:p-5">{["South elevation", "Mechanical room", "Primary terrace"].map((label, index) => <div key={label} className={`portal-photo portal-photo-${index + 1} relative aspect-[4/3] overflow-hidden`}><div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/70 to-transparent p-4 pt-10 text-white"><p className="text-xs">{label}</p><Camera aria-hidden="true" className="size-4 text-white/60" /></div></div>)}</div></Panel>
    </main>
  );
}
