import { Bullets, Card, RDHeader } from "../_components";

export default function DesignPage() {
  return <div className="space-y-5"><RDHeader title="Design" subtitle="Approved visual direction, floor-plan priorities and physical brand cues for the future Outpost." />
    <Card title="Approved brand direction" tag="Current"><Bullets items={["Name: Outpost Coffee & Moto.","Tagline: Caffeine and Gasoline.","Approved logo direction: refined option 2 with corrected lettering.","Historical family photograph of Thomas Woolstinholme on the Kamas SS hill is part of the brand story.","Overall tone: moody, premium, understated mountain workshop rather than novelty moto décor."]}/></Card>
    <Card title="Material palette"><Bullets items={["Charcoal / near-black base, warm cream and restrained gold accents.","Black steel, timber, concrete, leather and warm task lighting.","Smaller, quieter signage preferred over oversized branding.","Mountain/outpost graphics can appear as subtle environmental layers rather than dominant decoration."]}/></Card>
    <Card title="Ideal two-level floor plan"><Bullets items={["Ground floor: coffeehouse at the public frontage, curated retail/showroom, two Outpost Moto bays, one APRISM bay, restrooms, storage and rear service access.","Upper floor: separate Outpost office, APRISM office, shared admin/work area and a 6–8 person meeting room.","Customer circulation should never cross active workshop circulation.","Workshop should remain visually connected through glazing while controlling sound, fumes and safety.","Allow future bay or café expansion wherever the site makes that possible."]}/></Card>
    <Card title="Reference concepts"><Bullets items={["Outpost Depot + Workshop: roughly 3,900 SF with parking, patio, motorcycle circulation and expansion planning.","Three exterior container + steel concepts were developed; concept two was the preferred direction because the container element felt integrated rather than applied.","Mountain View Commons 30 × 60 ft published plan became the strongest real-plan adaptation reference.","A cutaway isometric version of the ideal building was requested to communicate the full two-level arrangement."]}/></Card>
    <Card title="Experience details"><Bullets items={["Coffee bar should be immediately legible from the entrance.","Motorcycle display should feel curated, not crowded.","Community table and lounge should connect café and Moto audiences without blocking circulation.","Rear roll-up access, covered bike parking and outdoor gathering space materially improve the concept.","The visual goal is a place that feels credible to riders and still comfortable to non-riders, families and locals."]}/></Card>
  </div>;
}
