import { CalendarDays, Download, ExternalLink, FileText, MapPin } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { HealthBadge } from "@/components/portal/health-badge";
import { Panel } from "@/components/portal/portal-ui";
import { demoProperty, documents, maintenanceItems, propertySystems, serviceHistory, vendors } from "@/lib/portal-data";

type PropertyPageProps = { params: Promise<{ id: string }> };

export function generateStaticParams() { return [{ id: demoProperty.id }]; }

export async function generateMetadata({ params }: PropertyPageProps): Promise<Metadata> {
  const { id } = await params;
  if (id !== demoProperty.id) return { title: "Property not found" };
  return { title: demoProperty.name, description: `APRISM property stewardship record for ${demoProperty.name} in ${demoProperty.location}.`, openGraph: { images: [] }, twitter: { images: [] } };
}

export default async function PropertyDetailPage({ params }: PropertyPageProps) {
  const { id } = await params;
  if (id !== demoProperty.id) notFound();

  return (
    <main className="mx-auto max-w-[1480px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
      <div className="grid overflow-hidden border border-black/10 bg-[#171b19] text-white lg:grid-cols-[1.05fr_0.95fr]"><div className="portal-property-scene relative min-h-[24rem] p-6 sm:p-8"><div className="relative z-10 flex h-full flex-col justify-between"><Link href="/portal/properties" className="text-[0.55rem] font-semibold uppercase tracking-[0.16em] text-white/48">← Properties</Link><div><HealthBadge status={demoProperty.health} /><h1 className="mt-5 font-serif text-5xl leading-none sm:text-6xl">{demoProperty.name}</h1><p className="mt-4 flex items-center gap-2 text-xs uppercase tracking-[0.14em] text-white/48"><MapPin aria-hidden="true" className="size-4" />{demoProperty.location}</p></div></div></div><div className="grid grid-cols-2 gap-px bg-white/10"><div className="bg-[#171b19] p-5 sm:p-7"><p className="text-[0.52rem] uppercase tracking-[0.15em] text-white/34">Residence</p><p className="mt-3 text-sm">{demoProperty.type}</p></div><div className="bg-[#171b19] p-5 sm:p-7"><p className="text-[0.52rem] uppercase tracking-[0.15em] text-white/34">Size</p><p className="mt-3 text-sm">{demoProperty.size}</p></div><div className="bg-[#171b19] p-5 sm:p-7"><p className="text-[0.52rem] uppercase tracking-[0.15em] text-white/34">Built</p><p className="mt-3 text-sm">{demoProperty.built}</p></div><div className="bg-[#171b19] p-5 sm:p-7"><p className="text-[0.52rem] uppercase tracking-[0.15em] text-white/34">APRISM since</p><p className="mt-3 text-sm">April 2025</p></div><div className="col-span-2 flex items-center gap-3 bg-[#202421] p-5 text-xs text-white/55 sm:p-7"><CalendarDays aria-hidden="true" className="size-4 text-[#c7a76b]" />Next scheduled visit · {demoProperty.nextVisit}</div></div></div>
      <nav aria-label="Property sections" className="mt-5 flex gap-2 overflow-x-auto border border-black/10 bg-[#f8f7f2] p-2 text-[0.54rem] font-semibold uppercase tracking-[0.14em] text-black/45">{["Overview", "Systems", "Equipment", "History", "Documents", "Vendors", "Photos", "Calendar"].map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="shrink-0 px-4 py-3 transition hover:bg-black/[0.04] hover:text-black">{item}</a>)}</nav>
      <div id="overview" className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
        <Panel title="Property overview" eyebrow="Stewardship summary"><div className="grid gap-px bg-black/10 sm:grid-cols-2">{[["Current status", "Monitor · 1 action recommended"], ["Last inspection", demoProperty.lastInspection], ["Open issues", "2 · none critical"], ["Next scheduled visit", demoProperty.nextVisit], ["Upcoming maintenance", "4 tasks · next 45 days"], ["Property record", "Current as of Aug 24"]].map(([label, value]) => <div key={label} className="bg-[#f8f7f2] p-5"><p className="text-[0.5rem] uppercase tracking-[0.14em] text-black/34">{label}</p><p className="mt-2 text-sm">{value}</p></div>)}</div></Panel>
        <Panel title="Maintenance calendar" eyebrow="Upcoming" className="scroll-mt-20" action={<Link href="/portal/maintenance" className="text-[0.52rem] font-semibold uppercase tracking-[0.14em] text-[#80632d]">View calendar</Link>}><div id="calendar" className="divide-y divide-black/10 scroll-mt-24">{maintenanceItems.map((item) => <div key={item.title} className="flex items-center gap-4 px-5 py-4"><div className="flex size-11 shrink-0 flex-col items-center justify-center border border-black/12 bg-white"><span className="text-[0.45rem] uppercase text-black/35">{item.date.split(" ")[0]}</span><span className="font-serif text-lg">{item.date.split(" ")[1]}</span></div><div><p className="text-sm">{item.title}</p><p className="mt-1 text-xs text-black/38">{item.status}</p></div></div>)}</div></Panel>
      </div>
      <Panel title="Systems & equipment" eyebrow="Operating record" className="mt-5 scroll-mt-24"><div id="systems" className="divide-y divide-black/10 scroll-mt-24">{propertySystems.map((system) => <div key={system.name} className="grid gap-4 px-5 py-5 sm:grid-cols-[1fr_1fr_auto] sm:items-center sm:px-6"><div><h3 className="text-sm font-medium">{system.name}</h3><p className="mt-1 text-xs text-black/42">{system.detail}</p></div><p className="text-xs text-black/42">{system.service}</p><HealthBadge status={system.status} /></div>)}</div><div id="equipment" className="scroll-mt-24 border-t border-black/10 bg-black/[0.02] px-5 py-4 text-xs text-black/42 sm:px-6">Equipment inventory includes model, serial, warranty, vendor, service interval, and supporting documents for each tracked asset.</div></Panel>
      <div className="mt-5 grid gap-5 xl:grid-cols-2">
        <Panel title="Service history" eyebrow="Recent activity"><div id="history" className="divide-y divide-black/10 scroll-mt-24">{serviceHistory.map((item) => <div key={item.title} className="grid grid-cols-[4.5rem_1fr] gap-4 px-5 py-4 sm:px-6"><p className="text-xs font-medium text-[#80632d]">{item.date}</p><div><p className="text-sm">{item.title}</p><p className="mt-1 text-xs text-black/40">{item.detail}</p></div></div>)}</div></Panel>
        <Panel title="Documents" eyebrow="Property library"><div id="documents" className="divide-y divide-black/10 scroll-mt-24">{documents.map((document) => <div key={document.name} className="flex items-center gap-4 px-5 py-4 sm:px-6"><span className="flex size-10 shrink-0 items-center justify-center border border-black/10 bg-white"><FileText aria-hidden="true" className="size-4 text-[#80632d]" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm">{document.name}</p><p className="mt-1 text-xs text-black/38">{document.type} · {document.updated}</p></div><Download aria-hidden="true" className="size-4 text-black/30" /></div>)}</div></Panel>
      </div>
      <Panel title="Vendor contacts" eyebrow="Approved network" className="mt-5"><div id="vendors" className="grid gap-px bg-black/10 scroll-mt-24 sm:grid-cols-3">{vendors.map((vendor) => <article key={vendor.name} className="bg-[#f8f7f2] p-5"><p className="text-[0.5rem] uppercase tracking-[0.14em] text-[#80632d]">{vendor.specialty}</p><h3 className="mt-4 font-serif text-2xl">{vendor.name}</h3><p className="mt-2 text-xs text-black/42">Primary contact · {vendor.contact}</p><button type="button" className="mt-6 inline-flex items-center gap-2 text-[0.52rem] font-semibold uppercase tracking-[0.13em] text-black/55">Contact details <ExternalLink aria-hidden="true" className="size-3" /></button></article>)}</div></Panel>
      <Panel title="Property photos" eyebrow="Visual record" className="mt-5"><div id="photos" className="grid gap-3 p-4 scroll-mt-24 sm:grid-cols-3 sm:p-5">{["South elevation", "Mechanical room", "Primary terrace", "Great room", "Entry snowmelt", "Utility corridor"].map((label, index) => <div key={label} className={`portal-photo portal-photo-${(index % 3) + 1} relative aspect-[4/3] overflow-hidden`}><p className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4 pt-12 text-xs text-white">{label}</p></div>)}</div></Panel>
    </main>
  );
}
