import { Bullets, Card, RDHeader } from "../_components";

export default function FinancialsPage() {
  return <div className="space-y-5"><RDHeader title="Financials" subtitle="Working feasibility assumptions for Outpost. Planning only, not live accounting." />
    <Card title="Development frame" tag="Planning"><Bullets items={["A development target of about $800,000 has been used for the larger Outpost concept, including site/buildout, café, moto equipment, soft costs and contingency.","The preferred funding path is to avoid committing until the location and operating model can support debt service without exceptional growth assumptions.","APRISM LLC remains the umbrella and brand/IP owner; operating structure can be separated later if financing or risk management calls for it."]}/></Card>
    <Card title="Coalville base case"><Bullets items={["Base rent assumption used: $3,667/month.","NNN/CAM + utilities planning allowance: about $1,500/month.","Owner compensation scenarios modeled at $4,000 / $6,000 / $8,000 per month.","Key operating metrics: coffee transactions/day, moto billable hours/day, reserve requirement and gross margin."]}/></Card>
    <Card title="Downside cases"><Bullets items={["Winter downside model: coffee revenue -30% and moto revenue -25% for four months.","Bad-winter stress case: coffee -40%, moto -35%, with utilities and payroll +10%.","The decision standard is not whether the concept can work in a strong season, but whether it remains survivable through a weak winter without draining APRISM."]}/></Card>
    <Card title="Moto contribution"><Bullets items={["Existing garage-based service capability gives Outpost a lower-risk operating bridge before a full facility opens.","Target throughput discussed: roughly 4–5 motorcycles per week as the shop proves demand.","Service, tires, accessories, detailing, storage, pickup/delivery and inspections are potential higher-margin support lines."]}/></Card>
    <Card title="Property acquisition guardrails"><Bullets items={["Owner-user flex/industrial buy box: roughly 4,000–8,000 SF and divisible where possible.","Target DSCR: at least 1.30×.","Post-close reserves: at least six months of property plus household/business obligations.","Any purchase must pencil without assuming extraordinary APRISM or Outpost growth."]}/></Card>
    <Card title="Still to complete"><Bullets items={["Full café revenue model by transactions/day and average ticket.","Moto labor, parts and seasonal capacity model by bay and technician.","Combined staffing plan and loaded payroll.","COGS, occupancy, insurance and marketing assumptions by candidate site.","5-year P&L, cash flow, breakeven and lender/investor case once a realistic site is selected."]}/></Card>
  </div>;
}
