import type { Metadata } from "next";
import { ArrowLeft, Building2, CheckCircle2, CreditCard, Download, Landmark, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BillingStatusBadge, DemoBillingNotice, labelBillingStatus } from "@/components/portal/billing-ui";
import { formatBillingDate, formatMoney } from "@/lib/billing";
import { getInvoiceByNumber } from "@/lib/billing-records";
import { createInvoiceCheckout } from "../actions";

export const metadata: Metadata = { title: "Invoice" };

const paymentMessages: Record<string, string> = {
  processing: "Stripe received your payment submission. Bank payments can remain pending while the transfer clears; this invoice updates only after a verified Stripe event.",
  cancelled: "Payment was cancelled. No payment status was changed.",
  unavailable: "Secure payment processing is not available right now. Please contact APRISM for assistance.",
  invalid: "The payment request was invalid.",
  "not-payable": "This invoice does not currently have a payable balance.",
  "ach-unavailable": "ACH is currently available only for USD invoices.",
};

function paymentTerms(days: number) {
  if (days === 0) return "Payment Terms: Due on receipt unless otherwise agreed in writing.";
  return `Payment Terms: Net ${days}. Payment is due within ${days} calendar days of the invoice date unless otherwise agreed in writing.`;
}

export default async function InvoiceDetailPage({ params, searchParams }: { params: Promise<{ invoiceNumber: string }>; searchParams: Promise<{ payment?: string }> }) {
  const [{ invoiceNumber }, query] = await Promise.all([params, searchParams]);
  const { mode, invoice } = await getInvoiceByNumber(invoiceNumber);
  if (!invoice) notFound();

  const paymentMessage = query.payment ? paymentMessages[query.payment] : null;
  const payable = mode === "live" && invoice.amountDue > 0 && ["sent", "partially_paid", "overdue"].includes(invoice.status);

  return <main className="mx-auto max-w-[1200px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
    <div className="print-hidden mb-6 flex flex-wrap items-center justify-between gap-3"><Link href="/portal/invoices" className="inline-flex items-center gap-2 text-[0.6rem] font-semibold uppercase tracking-[0.14em] text-black/48"><ArrowLeft aria-hidden="true" className="size-4" />All invoices</Link>{invoice.pdfStoragePath ? <Link href={`/portal/invoices/${encodeURIComponent(invoice.invoiceNumber)}/pdf`} className="inline-flex min-h-10 items-center gap-2 border border-black/12 bg-white px-4 text-[0.58rem] font-semibold uppercase tracking-[0.13em]"><Download aria-hidden="true" className="size-4" />Download PDF</Link> : null}</div>
    {mode === "preview" ? <DemoBillingNotice /> : null}
    {paymentMessage ? <div role="status" className="print-hidden mt-5 border border-[#8c6f3c]/25 bg-[#8c6f3c]/8 px-5 py-4 text-sm leading-6 text-[#6f562c]">{paymentMessage}</div> : null}
    <article className="mt-5 overflow-hidden border border-black/10 bg-[#fbfaf6] shadow-[0_24px_70px_rgba(22,25,23,0.08)]">
      <header className="grid gap-8 bg-[#151918] px-6 py-8 text-white sm:px-10 sm:py-10 lg:grid-cols-[1fr_auto] lg:items-start"><div><p className="text-lg font-semibold tracking-[0.34em]">APRISM</p><p className="mt-3 text-[0.58rem] font-semibold uppercase tracking-[0.2em] text-[#d1b477]">Luxury Asset Stewardship</p><h1 className="mt-8 font-serif text-4xl leading-none sm:text-5xl">Managing What Matters.</h1></div><div className="lg:text-right"><p className="text-[0.58rem] font-semibold uppercase tracking-[0.18em] text-white/35">Invoice</p><p className="mt-2 font-serif text-2xl">{invoice.invoiceNumber}</p><div className="mt-4 flex lg:justify-end"><BillingStatusBadge status={invoice.status} /></div></div></header>
      <section className="grid gap-px bg-black/10 sm:grid-cols-2 lg:grid-cols-4"><div className="bg-[#fbfaf6] p-5 sm:p-6"><p className="text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-black/35">Client / company</p><p className="mt-3 text-sm font-semibold">{invoice.clientName}</p></div><div className="bg-[#fbfaf6] p-5 sm:p-6"><p className="text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-black/35">Invoice date</p><p className="mt-3 text-sm">{formatBillingDate(invoice.issueDate)}</p></div><div className="bg-[#fbfaf6] p-5 sm:p-6"><p className="text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-black/35">Due date</p><p className="mt-3 text-sm">{formatBillingDate(invoice.dueDate)}</p></div><div className="bg-[#fbfaf6] p-5 sm:p-6"><p className="text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-black/35">Terms</p><p className="mt-3 text-sm">Net {invoice.paymentTermsDays}</p></div></section>
      <section className="grid gap-8 px-6 py-8 sm:px-10 lg:grid-cols-2"><div><p className="text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-black/35">Work order</p><p className="mt-3 flex items-start gap-2 text-sm"><Building2 aria-hidden="true" className="mt-0.5 size-4 text-[#8c6f3c]" />{invoice.workOrderTitle ?? "Direct account service"}</p></div><div><p className="text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-black/35">Service location</p><p className="mt-3 text-sm">{invoice.serviceLocation ?? "Account-level service"}</p></div></section>
      <section className="border-y border-black/10"><div className="hidden grid-cols-[minmax(0,1fr)_90px_130px_130px] gap-4 border-b border-black/10 bg-[#f1efe8] px-10 py-3 text-[0.55rem] font-semibold uppercase tracking-[0.14em] text-black/38 sm:grid"><span>Description</span><span>Quantity</span><span>Unit price</span><span className="text-right">Amount</span></div>{invoice.items.map((item) => <div key={item.id} className="grid gap-4 border-b border-black/10 px-6 py-5 last:border-0 sm:grid-cols-[minmax(0,1fr)_90px_130px_130px] sm:px-10 sm:items-center"><div><p className="text-sm font-medium">{item.description}</p>{item.serviceDate ? <p className="mt-1 text-xs text-black/38">Service date · {formatBillingDate(item.serviceDate)}</p> : null}</div><div><p className="text-[0.55rem] font-semibold uppercase tracking-[0.12em] text-black/32 sm:hidden">Quantity</p><p className="mt-1 text-sm sm:mt-0">{item.quantity} {item.unit}</p></div><div><p className="text-[0.55rem] font-semibold uppercase tracking-[0.12em] text-black/32 sm:hidden">Unit price</p><p className="mt-1 text-sm sm:mt-0">{formatMoney(item.unitPrice, invoice.currency)}</p></div><div className="sm:text-right"><p className="text-[0.55rem] font-semibold uppercase tracking-[0.12em] text-black/32 sm:hidden">Amount</p><p className="mt-1 text-sm font-semibold sm:mt-0">{formatMoney(item.amount, invoice.currency)}</p></div></div>)}</section>
      <section className="grid gap-8 px-6 py-8 sm:px-10 lg:grid-cols-[1fr_360px]"><div><p className="max-w-xl text-xs leading-6 text-black/44">{paymentTerms(invoice.paymentTermsDays)}</p>{invoice.notes ? <p className="mt-4 max-w-xl text-xs leading-6 text-black/44">{invoice.notes}</p> : null}</div><dl className="space-y-3 text-sm"><div className="flex justify-between gap-5"><dt className="text-black/45">Subtotal</dt><dd>{formatMoney(invoice.subtotal, invoice.currency)}</dd></div><div className="flex justify-between gap-5"><dt className="text-black/45">Tax</dt><dd>{formatMoney(invoice.tax, invoice.currency)}</dd></div><div className="flex justify-between gap-5 border-t border-black/10 pt-3 font-semibold"><dt>Total</dt><dd>{formatMoney(invoice.total, invoice.currency)}</dd></div><div className="flex justify-between gap-5"><dt className="text-black/45">Payments</dt><dd>−{formatMoney(invoice.amountPaid, invoice.currency)}</dd></div><div className="flex justify-between gap-5 border-t border-black/15 pt-4"><dt className="font-serif text-2xl">Balance due</dt><dd className="font-serif text-3xl text-[#80632d]">{formatMoney(invoice.amountDue, invoice.currency)}</dd></div></dl></section>
      {invoice.payments.length ? <section className="border-t border-black/10 px-6 py-7 sm:px-10"><h2 className="font-serif text-2xl">Payment activity</h2><div className="mt-4 divide-y divide-black/10 border-y border-black/10">{invoice.payments.map((payment) => <div key={payment.id} className="flex flex-wrap items-center justify-between gap-4 py-4 text-sm"><div><BillingStatusBadge status={payment.status} /><p className="mt-2 text-xs capitalize text-black/42">{payment.paymentMethod} · {formatBillingDate(payment.paidAt ?? payment.createdAt)}</p></div><p className="font-serif text-xl">{formatMoney(payment.amount, payment.currency)}</p></div>)}</div></section> : null}
    </article>
    <section id="payment" className="print-hidden mt-6 overflow-hidden border border-black/10 bg-[#171b19] text-white"><div className="grid gap-7 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[0.58rem] font-semibold uppercase tracking-[0.18em] text-[#d1b477]">Pay invoice</p><h2 className="mt-3 font-serif text-3xl">Secure hosted payment</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/44">Payment credentials are entered with Stripe, never in APRISM form fields. ACH is preferred; credit and debit cards are also supported.</p></div>{invoice.amountDue <= 0 ? <div className="flex items-center gap-2 text-sm text-[#d1b477]"><CheckCircle2 aria-hidden="true" className="size-5" />Paid in full</div> : <div className="flex min-w-[270px] flex-col gap-2"><form action={createInvoiceCheckout}><input type="hidden" name="invoiceNumber" value={invoice.invoiceNumber} /><input type="hidden" name="paymentMethod" value="ach" /><button type="submit" disabled={!payable} className="inline-flex min-h-12 w-full items-center justify-center gap-2 bg-[#d1b477] px-5 text-xs font-semibold uppercase tracking-[0.12em] text-[#171a19] transition hover:bg-[#dfc78f] disabled:cursor-not-allowed disabled:opacity-45"><Landmark aria-hidden="true" className="size-4" />ACH / Bank Account</button></form><form action={createInvoiceCheckout}><input type="hidden" name="invoiceNumber" value={invoice.invoiceNumber} /><input type="hidden" name="paymentMethod" value="card" /><button type="submit" disabled={!payable} className="inline-flex min-h-12 w-full items-center justify-center gap-2 border border-white/18 px-5 text-xs font-semibold uppercase tracking-[0.12em] text-white/75 transition hover:border-white/35 hover:text-white disabled:cursor-not-allowed disabled:opacity-35"><CreditCard aria-hidden="true" className="size-4" />Credit / Debit Card</button></form></div>}</div><div className="flex items-center gap-2 border-t border-white/10 px-6 py-4 text-[0.62rem] text-white/35 sm:px-8"><ShieldCheck aria-hidden="true" className="size-4 text-[#d1b477]" />Verified webhook confirmation controls invoice status. Browser responses are never trusted.{mode === "preview" ? " Demo payment controls are disabled." : ""}</div></section>
    <p className="mt-5 text-center text-[0.6rem] uppercase tracking-[0.14em] text-black/35">Invoice status · {labelBillingStatus(invoice.status)}</p>
  </main>;
}
