import { Bullets, Card, RDHeader } from "../_components";

export default function ConceptsPage() {
  return <div className="space-y-5"><RDHeader title="Concepts" subtitle="The operating idea, customer experience and physical format we have developed for Outpost Coffee & Moto." />
    <Card title="Core concept" tag="Current"><Bullets items={["Specialty coffee + real motorcycle service + curated gear + community under one roof.","Coffee drives daily traffic; motorcycle service drives higher-value transactions; community builds loyalty.","All-brand service with Harley-Davidson strength and Outpost Moto heritage.","Café only, not a full restaurant: bakery, locally supplied breakfast items and grab-and-go food rather than a full kitchen."]}/></Card>
    <Card title="Customer experience"><Bullets items={["Main Street/storefront arrival → coffee bar → curated Moto showroom/lounge → glazed visual connection → working motorcycle shop.","Keep customers physically separated from tools, exhaust and workshop hazards while preserving the theatre of the shop.","20–30 café seats, community table, merchandise/helmet display and one or two display motorcycles.","Rider-friendly outdoor area, covered motorcycle parking and room for rides, bike nights, MotoGP/watch events and private gatherings."]}/></Card>
    <Card title="Ideal combined building"><Bullets items={["Two Outpost Moto service bays plus one APRISM Property Services bay, with shop separation where needed.","Coffeehouse and retail at the public frontage; motorcycle service behind/rear with roll-up access.","Upper floor with separate Outpost and APRISM offices, shared admin area and a 6–8 person meeting room.","Storage, restrooms, strong circulation, visible workshop connection and space for future expansion.","Target property size has generally been 4,000–8,000 SF, divisible where possible; site target roughly 0.75–1.25 acre for a standalone build."]}/></Card>
    <Card title="Brand promise"><p className="text-[#f2eee5]">Outpost Coffee & Moto</p><p>Caffeine and Gasoline.</p><p>Coffee • Motorcycles • Community.</p><p>A premium mountain workshop aesthetic: timber, black steel, concrete, leather, warm lighting and restrained signage.</p></Card>
  </div>;
}
